version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
  api:
    build:
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: postgresql://postgres:postgres@db:5432/fastapi
      depends_on:
        - db